emersion/go-webdav

carddav/fs.go

The package comment is already present in [carddav.go](https://github.com/emersion/go-webdav/blob/f8d9f83cbc04bfb10f84848d3a2976345ce07bb0/carddav/carddav.go#L1-L2) file.
Having it in both places makes godoc show the documentation text twice. This can be seen at https://godoc.org/github.com/emersion/go-webdav/carddav at this time:

carddav: Remove duplicate package comment

---

carddav/carddav.go
carddav/client.go
internal/client.go
internal/elements.go

Basic sync-collection operation for client
partial implementation of #35

sync-collection for client

---

carddav/server.go

This pr adds handling of well-known URLs for both carddav and caldav. According to the [RFC 6764, Section 6](https://tools.ietf.org/html/rfc6764#section-6) the initial request for a client is a PROPFIND against `well-known/carddav`or `well-known/caldav`, which the server should reply to with a redirect to the proper endpoint (which here corresponds to the "/" url).
This might partially solve #30

Add handling for carddav/caldav well-known urls

---

internal/elements.go

In case of a card deletion, SyncCollection() responded with a SyncResponse.Deleted: [ "" ].
Instead of, a href should be returned together with a 404. Please see https://tools.ietf.org/html/rfc6578#section-3.2
The reason was the early exit (without a href/path) of Response.Path() in case of an error/404.
I slightly restructured Response.path() so that it remains simple and readable (without cascaded if's)

Return href together with a 404

---

internal/elements.go
internal/elements_test.go

Fixes #47.
Signed-off-by: Sebastien Binet <binet@cern.ch>

internal: use http.TimeFormat to marshal Time values

---

carddav/server.go

Some clients (e.g. Evolution) will not work properly without this. It is
up to the underlying backend to actually provide this data, the headers
will only be set if it is available.

Set ETag and Last-Modified if available

---

carddav/match.go
carddav/match_test.go

This is a continuation of #49
I addressed all your comments and removed two test cases that I think were a misunderstanding about the semantics of `DataRequest.AllProp`.
I did add handling of `carddav.PropFilter.IsNotDefined` because it seemed simple, let me know if I got that wrong there.
About the collation handling, I added the TODO, but it seems this needs support in the `TextMatch` type first, correct?

carddav: add filtering and matching helper functions

---

carddav/server.go
internal/internal.go
internal/server.go

Backends will need some way to signal that a precondition error occurred
(and specifying which one) without causing the server to return a 500.
This commit adds an exported function to create a specific error for
this. The existing error handling routine is slightly adapted to handle
this error in such a way that it (almost) returns the desired result.
Usage would be something like:
return "", carddav.PreconditionError("no-uid-conflict")
As is, this approach is missing a few things to be correct:
* Content-Type response header is text/plain, should be text/xml
* Response body is missing XML header (`<?xml ...`)
I'd like to get your opinion as early as possible before I start writing
more code.
Other approaches I could think of would be creating another, more
specific error type for this, …

Add error type representing DAV/XML errors

---

caldav/caldav.go
caldav/elements.go
caldav/server.go

The basic types related to queries and filtering are missing some
features specified in the RFC (as also noted in the TODO comments). This
adds several of the missing elements, working towards being able to
handle all RFC-compliant queries.
The work is not fully done, e.g. the collation for text-match is still
not handled, but it's getting pretty close.

caldav: extend query filter types

---

caldav/server.go
carddav/server.go
internal/elements.go
internal/internal.go
internal/server.go

Small error improvements

---

server.go

This can be used by backends to influence the status code returned to
clients for errors that occurred in the backend.

Add exported function to create `HTTPError`

---

caldav/caldav.go
caldav/elements.go
caldav/server.go
carddav/carddav.go
carddav/elements.go
carddav/server.go
elements.go
server.go

Currently, the user principal path and the home set path are both
hardcoded to "/", for both CalDAV and CardDAV. This poses a challenge if
one wishes to run a CardDAV and CalDAV server in the same server.
This commit introduces the concept of a UserPrincipalBackend. This
backend must provide the locations for the user principal as well as the
home sets. The CardDAV and CalDAV servers act accordingly.
The individual servers will continue to work as before (including the
option of keeping everything at "/"). If one wishes to run CardDAV and
CalDAV in parallel, the new `webdav.ServeUserPrincipal()` can be used,
which will use the UserPrincipalBackend interface to serve a common user
principal for both servers (if so desired, can be used for a single one
also).
Note that the storage backend …

Support custom user principal and home set paths

---

caldav/server.go

Still missing a few features, but works to a certain extend. Requires an update to the backend interface to support the operations.

Implement GET/HEAD/PUT for calendar objects

---

server.go

A principal may represent something else than a user, for instance
it may represent a group.
Also rename UserPrincipalPath to CurrentUserPrincipalPath, because
the principal being served may not represent the current user.
cc @bitfehler

webdav: rename ServeUserPrincipal to ServePrincipal

---

caldav/caldav.go

CalDAV imposes a set of constraints on iCal Calendar objects. They are
spelled out in [RFC 4791, section 4.1][1]. Add an exported function to
validate a calendar according to those constraints, and return data that
is necessary for further CalDAV processing and which can only be
extracted if the calendar meets these constraints.
[1]: https://datatracker.ietf.org/doc/html/rfc4791#section-4.1

Add function to validate calendar for CalDAV

---

caldav/server.go
carddav/server.go

This makes it a little less ambiguous (and, in case of Go clients, a lot
easier) that clients should follow the redirect by sending the same
PROPFIND request, including body, to the new location.
See also the documentation of [http.Client.Do()][1] and the comments in
[http.redirectBehavior()][2].
Confirmed to not make a difference for Evolution and Thunderbird
clients.
[1]: https://pkg.go.dev/net/http#Client.Do
[2]: https://cs.opensource.google/go/go/+/refs/tags/go1.18.2:src/net/http/client.go;drc=d8762b2f4532cc2e5ec539670b88bbc469a13938;l=502

carddav/caldav: use 308 for .well-known redirects

---

caldav/caldav.go
caldav/server.go

Allow the backend to provide a value for the `getcontentlength` property
as described in [RFC 2518 section 13.4][1].
The implementation treats is as optional, allthough it is a required
property per RFC. Most clients do perfectly fine without it, though.
Properly setting this in the backend makes the CalDAV collection
listable with clients that do require it, e.g. cadaver.
[1]: https://datatracker.ietf.org/doc/html/rfc2518#section-13.4

caldav: add support for getcontentlength property

---

internal/client.go

One method to find the current user principal URL is to request the
`/.well-known/carddav` URL (see [RFC 6764, section 6][1]).
Add this as second attempt if the discovery via the configured endpoint
fails. This helps the client discover resources even if just given an
endpoint without path.
[1]: https://datatracker.ietf.org/doc/html/rfc6764#section-6

client: support redirects in FindCurrentUserPrincipal

---

carddav/match.go
carddav/match_test.go

I am a bit unsure whether or not this makes sense and would like to solicit your input :slightly_smiling_face: 
I would say that this implementation makes the behavior of the `Filter()` function more correct. However, a case could be made that this performs work that e.g. backend may have already performed. Example: a hypothetical database backend might construct a database query that already returns the objects reduced to the requested properties (and/or only those matching the query). In this case, the current implementation would simply create a copy of each object with no further benefit.
However, I would argue that that is a very advanced use case, and such a backend would probably not be using the `Filter()` function in the first place. Also, while I could imagine such a …

carddav: do property filtering in match.Filter() 

---

client.go

Using webdav in [juicefs server](https://github.com/juicedata/juicefs) gives the error 'too many open files'
```bash
(pprof) top
Showing nodes accounting for 643, 99.69% of 645 total
Dropped 76 nodes (cum <= 3)
Showing top 10 nodes out of 46
flat  flat%   sum%        cum   cum%
640 99.22% 99.22%        640 99.22%  runtime.gopark
3  0.47% 99.69%          3  0.47%  syscall.Syscall
0     0% 99.69%         20  3.10%  bufio.(*Reader).Peek
0     0% 99.69%         21  3.26%  bufio.(*Reader).fill
0     0% 99.69%         20  3.10%  github.com/emersion/go-webdav.(*Client).Create.func1
0     0% 99.69%         20  3.10%  github.com/emersion/go-webdav.(*fileWriter).Close
0     0% 99.69%         20  3.10%  github.com/emersion/go-webdav/internal.(*Client).Do
0     0% 99.69%         20  3.10% …
```

fix: Response body was not closed causing the goroutine leak

---

carddav/client.go

See RFC 6764 section 6 item 3.

carddav: use "/.well-known/carddav/" as initial context path in Discover

---

carddav/carddav_test.go

As the implementation evolves, it will be necessary to have more tests
to assert we don't break anything when making changes. This commit
introduces a test setup to test that server and client can handle the
address book discovery with various parameters. The test setup should be
easily extendable to cover even more ground as needed.

carddav: end-to-end test address book discovery

---

caldav/caldav.go

If in a calendar file VTIMEZONE component is after VEVENT then on the second pass of the `comp` loop `uid` is not blank (set from VEVENT) but `compUID` is blank (set from VTIMEZONE). This wrongly causes error `conflicting UID values in calendar`.

caldav: fix validation error when VTIMEZONE is after VEVENT

---

carddav/carddav_test.go
carddav/server.go

See #100 for details. Obsoletes #99.

carddav: switch to one static path layout

---

caldav/server.go
carddav/carddav_test.go

This is like #101 but for CalDAV.
There might be some opportunities for shared code, but the devil is in the details. I'd like to wait for support for multiple calendars/address books - it will be fairly easy now, and after that there should be no more big changes. Then I am happy to give it a once-over with regards to code sharing.
Also adds tests similar to the CardDAV ones.

caldav: use same static path layout as carddav

---

caldav/caldav.go
carddav/carddav.go
server.go

This is done properly in the carddav and caldav packages, but the custom function does not know what the user intends to serve, so it must be passed in from the user. Without this, certain clients (e.g. DAVx5) will be unable to discover endpoints served this way.
Also slightly extend the supported methods returned on OPTIONS requests. REPORT is properly supported, the others are mostly for not giving clients the impression that the resources are read-only.

Support setting capabilities in ServePrincipal()

---

caldav/server.go
caldav/server_test.go

I started using this project to export tasks over CalDav, more
specifically to `Reminders` on `iOS`/`macOS`. I quickly realized that
even if you specify that `SupportedComponentSet` contains `VTODO`, that
isn't reflected properly wher doing the `PROPFIND`.
This PR should fix that, while keeping the behaviour of defaulting to
`VEVENT` for propfind. Also added some tests to make sure that I didn't
break anything (Which I hope I didn't :sweat_smile:).

Make sure that `SupportedComponentSet` is properly reflected in `PROPFIND`

---

caldav/server.go
caldav/server_test.go

It seems like the Reminders app in `iOS`/`macOS` does this request as the first thing when setting up an account, so it seems reasonable to handle it for us.
This just returns the most basic current-user-principal now, but that should hopefully be enough to continue the process.

Make sure to handle a PROPFIND to `/`

---

internal/elements.go

This CL corrects the following bug uncovered by staticcheck:
```
internal/elements.go:148:6: this comparison is always true (SA4023)
internal/elements.go:146:18: the lhs of the comparison gets its value from here and has a concrete type
```

internal: fix always-true interface comparison

---

caldav/match.go
caldav/match_test.go

Matches on open time ranges (i.e. no end date) were not properly handled, as `end` is simply the zero time, which confuses the `.Before()` and `.After()` logic employed here.
This commit fixes that by adding the appropriate `.IsZero()` checks and also adds a test case.
The current behavior unfortunately broke compatibility with DAVx5, which by default queries only events less than 90 days ago (by using an open time range).

caldav: fix match on open time ranges

---

caldav/server.go
caldav/server_test.go

This was missing for proper multi-calendar support.
--
Not sure why this wasn't added in #127, but it looks like just oversight to me? A query (a.k.a. a REPORT request) has to be made against a specific calendar (or a calendar object resource), so the backend has to know which one.

caldav: add path to interface QueryCalendarObjects

---

carddav/carddav_test.go
carddav/server.go
server.go

This is the equivalent of #127 (and #140) for CardDAV and finally allows backends to serve different address books to different users.
While I'm breaking the interface, correct one last instance of "Addressbook" to "AddressBook" (in `AddressBookHomeSetPath`).

carddav: support multiple address books

---

carddav/carddav_test.go
carddav/elements.go
carddav/server.go

Now that the handling for multiple address books is in place, this commit adds initial support for creation and deletion of address books.
These operations obviously require support from the backend, so the interface gains two new methods. All properties of the address book passed to `CreateAddressBook()` may be unset, except for the path (e.g. when a client sends a MKCOL request without a body. It is up to the backend to put any desired default values in place. As is, the parsing of the request body still needs some improvements, but correctly handles the most common properties.
Using this as is (in tokidoki), I can successfully create and delete address books using DavX5. The validation is not great yet, but since this touches the interface again, I wanted to make sure early on that …

carddav: support address book creation/deletion

---

caldav/server.go

It seems like e.g. Apples reminders likes to send `PropPatch`, and
currently this just fills up my logs because of the panic. I thought it
would be better to signal that this isn't supported yet, which should
hopefully make it easier to dig through the logs.

Return proper HTTP 501 instead of panicing.

---

caldav/server.go
carddav/server.go

Both the displayname and the description can be absent for both calendars and address books. If this is the case they should not show up in PROPFIND responses as empty string.

*: displayname, desription are optional

---

internal/server.go

Responses that contain propstat elements do not contain their own top-level status element, only the status elements inside the propstat element.
See https://datatracker.ietf.org/doc/html/rfc4918#section-14.24 or any of the examples for PROPFIND/PROPPATCH, starting e.g. here: https://datatracker.ietf.org/doc/html/rfc4918#section-9.1.3

internal: no status element in propstat responses

---

carddav/carddav_test.go

carddav part of https://github.com/emersion/go-webdav/pull/150

carddav: add unit test for CardDAV mkcol

---

internal/server.go

see https://datatracker.ietf.org/doc/html/rfc4918#section-8.2

internal: use application/xml instead of text/xml which is deprecated

---

caldav/server.go
carddav/server.go
internal/server.go
server.go

NewPropFindResponse uses callbacks to lazily build the response. However, some props are static: they don't require any processing to generate. Add a small helper to reduce boilerplate a bit.

internal: add PropFindValue

---

caldav/client.go

This change set adds support for correctly encoding the prop filters into calendar requests.
Example Request with this change set:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<calendar-query
xmlns="urn:ietf:params:xml:ns:caldav">
<prop
xmlns="DAV:">
<calendar-data
xmlns="urn:ietf:params:xml:ns:caldav">
<comp
xmlns="urn:ietf:params:xml:ns:caldav" name="VCALENDAR">
<comp
xmlns="urn:ietf:params:xml:ns:caldav" name="VEVENT">
<prop
xmlns="urn:ietf:params:xml:ns:caldav" name="UID">
</prop>
<prop
xmlns="urn:ietf:params:xml:ns:caldav" name="ATTENDEE">
</prop>
</comp>
</comp>
</calendar-data>
<getlastmodified
xmlns="DAV:">
</getlastmodified>
<getetag
xmlns="DAV:">
</getetag>
</prop>
<filter
xmlns="urn:ietf:params:xml:ns:caldav">
<comp-filter
xmlns="urn:ietf:params:xml:ns:caldav" …
```

Support prop-filter in client requests

---

caldav/caldav.go
caldav/client.go
caldav/elements.go

I needed the expand request for a project I'm working on (wanted recurring events to show at the correct date), so I went ahead and added it!
This is a pull request fixing my previous pull request that had import renames polluting the commit history

caldav: add expand request to client

---

internal/server.go

The previous code failed to properly handle PROPFIND with an empty request body (RFC 4918 section 9.1) for XML content type requests.
Refactor the logic to always consider PROPFIND requests with empty request bodies as "allprop" requests, regardless of content type.
There is no need to worry about the request's content type if the request body is empty anyway, so only parse if we know it is not.

internal/server: handle "allprop" with empty request and XML content type
